### ISSUE TITLE
IPAddressPool is too short

### ISSUE THREAD

**Issue by RicHincapie** [RicHincapie/multi-cluster-istio-kind#3]
In each cluster, MetalLb has a very narrow adresspool:
````
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster1
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.10-172.18.0.12
````

This creates issues when requiring more externalLB.

````
envoy-httpbin-dedicated-gateway-c4239473   LoadBalancer   10.96.185.236   <pending>     80:30664/TCP                                                                                                                                                                5m8s
````
